apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: my-php-app
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: my-php-app
    spec:
      containers:
      - name: mysql
        image: mysql
        ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP
        volumeMounts:
        - name: mysql-vm
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass-root
              key: password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-project
              key: password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-project
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-project
              key: password
      volumes:
      - name: mysql-vm
    hostPath:
      # directory location on host
      path: /mnt/data/storage
      # this field is optional
      type: DirectoryOrCreate
