apiVersion: v1
kind: Pod                                            # 1
metadata:
  name: nginx-frontend
  labels:
    app: nginx-frontend                                 # 2
spec:
  volumes:
  - name: project-volume
      persistentVolumeClaim:
        claimName: data                               # 3
  containers:
    - image: sergz99/nginx-symfony # 4
      name: nginx-frontend                              # 5
      ports:
        - containerPort: 80                          # 6
      volumeMounts:
      - mountPath: /project
        name: project-volume
