apiVersion: v1
kind: Pod                                            # 1
metadata:
  name: nginx-frontend2
  labels:
    app: nginx-frontend2                                 # 2
spec:
  volumes:
  - name: project-volume
    hostPath:
      # directory location on host
      path: /mnt/data
      # this field is optional
      type: DirectoryOrCreate                                                  # 3
  containers:
    - image: sergz99/nginx-symfony # 4
      name: nginx-frontend2                              # 5
      ports:
        - containerPort: 80                          # 6
      volumeMounts:
      - mountPath: /project
        name: project-volume
