apiVersion: v1
kind: Service              # 1
metadata:
  name: nginx-service-lb2
spec:
  type: LoadBalancer       # 2
  ports:
  - port: 80               # 3
    protocol: TCP          # 4
    targetPort: 80         # 5
  selector:                # 6
    app: nginx-frontend2       # 7
