---
- hosts: all
  become_user: root
  vars_prompt:
    - name: token
      prompt: What is your token?                                                                                                                         A  
  tasks:
   - name: Return all secrets from a path
     ansible.builtin.debug:
       msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv/smtp token={{ token }} url=http://192.168.100.100:8200') }}"
