---
- hosts: all
  become_user: root
  tasks:
   - name: Return all secrets from a path
     ansible.builtin.debug:
       msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret/giant token=myroot url=http://localhost:8200') }}"
