---
- hosts: all
  become_user: root
  tasks:
   - name: Return all secrets from a path
     ansible.builtin.debug:
       msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv/{{ service }}:{{ login }} token=myroot url=http://192.168.100.100:8200') }}"
