apiVersion: v1
kind: Pod
metadata:
  name: nginx-frontend
  labels:
    app: nginx-frontend
spec:
  volumes:
  - name: project-volume
    hostPath:
      # directory location on host
      path: /hosthome/useradmin/data
      # this field is optional
      type: Directory                                                  # 3
  - name: nginx-config
    configMap:
      name: nginx-config
  containers:
    - name: nginx-frontend
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
      - mountPath: /project
        name: project-volume
      - name: nginx-config
        mountPath: /etc/nginx/nginx.conf
        subPath: nginx.conf
