apiVersion: v1
kind: Pod                                            # 1
metadata:
  name: node
  labels:
    app: node                                 # 2
spec:
  volumes:
  - name: project-volume
    hostPath:
      # directory location on host
      path: /hosthome/useradmin/data
      # this field is optional
      type: DirectoryOrCreate                                                  # 3
  containers:
    - image: sergz99/nginx-symfony # 4
      name: node                              # 5
      volumeMounts:
      - mountPath: /project
        name: project-volume
