apiVersion: v1
kind: Service              # 1
metadata:
  name: php
spec:
  type: LoadBalancer       # 2
  ports:
  - port: 9000               # 3
    protocol: TCP          # 4
    targetPort: 9000         # 5
  selector:                # 6
    app: php       # 7
