apiVersion: v1
kind: Pod                                            # 1
metadata:
  name: php
  labels:
    app: php                                 # 2
spec:                                                # 3
  containers:
    - image: sergz99/php-symfony # 4
      name: php                              # 5
      ports:
        - containerPort: 80                          # 6
