apiVersion: v1
kind: Pod                                            # 1
metadata:
  name: php1
  labels:
    app: php1                                 # 2
spec:                                                # 3
  volumes:
  - name: project-volume
    hostPath:
      # directory location on host
      path: /hosthome/useradmin/data
      # this field is optional
      type: DirectoryOrCreate
  containers:
    - image: sergz99/php-symfony # 4
      name: php1                              # 5
      ports:
        - containerPort: 9000                          # 6
      volumeMounts:
      - mountPath: /project
        name: project-volume
