---
- hosts: all
  become_user: root
  gather_facts: false
  tasks:
  - name: Set a hostname
    ansible.builtin.hostname:
        name: web01
  - name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
    ansible.builtin.user:
     name: johnd
     comment: John Doe
     uid: 1040
     group: vagrant
