
---
- hosts: all 
  become: true
  gather_facts: no
 
  tasks:
   
   - name: Updates apt cache
     apt: update_cache=true    
   
   - name: Install required system packages
     apt: name=ca-certificates state=latest update_cache=yes

   - name: Install required system packages
     apt: name=wget state=latest update_cache=yes

   - name: Install required system packages
     apt: name=net-tools state=latest update_cache=yes

   - name: Install required system packages
     apt: name=gnupg state=latest update_cache=yes

   - name: Add OpenVPN GPG apt Key
     apt_key:
       url: https://as-repository.openvpn.net/as-repo-public.gpg
       state: present
   
   - name: Add repository
     apt_repository:
       repo: deb http://as-repository.openvpn.net/as/debian focal main
       state: present
       filename: openvpn-as-repo
       update_cache: no
   
   - name: Update apt and install openvpn
     apt: update_cache=yes name=openvpn-as state=latest
