name: Deploy_to_MB_instances

on:
  workflow_dispatch:
    inputs:
      DEPLOY_HOST:
        description: 'Host to deploing'     
        required: true
        default: 'stage' 
        type: choice
        options:
        - prod
        - stage
      DEPLOY:
        description: 'DEPLOY'
        required: false 
        type: boolean

jobs:
  Deploy_docker_image:
    name: example
    runs-on: [self-hosted, linux, X64, stage]
    if: ${{ github.event.inputs.DEPLOY }} == 'true'
    
    steps:
    - name: Set deploy variables
      run: |
        if [[ "${{ github.event.inputs.DEPLOY_HOST }}" == "stage" }} ]]; then
            echo "WORK_DIR=${{ secrets.STAGING_WORK_DIR }}" >> $GITHUB_ENV
        fi
        if [[ "${{ github.event.inputs.DEPLOY_HOST }}" == "prod" }} ]]; then
            echo "WORK_DIR=${{ secrets.PROD_WORK_DIR }}" >> $GITHUB_ENV
        fi

    - name: Deploy
      id: deploy
      run: |
        cd ${{ env.WORK_DIR }}
        ls -la
