# This is a basic workflow to help you get started with Actions

name: CI

on: workflow_dispatch

jobs:
  test-yaml-reader:
    runs-on: self-hosted
    name: Test read-yaml
    steps:
      - name: Run read-yaml action
        id: yaml-data
        uses: KJ002/read-yaml@main      # You may wish to replace main with a version tag such as '1.6' etc.
        with:
          file: '/home/sergeyzuev/odoo_instances/odoo-test-pg-exp/MODULES_CHANGELOG.yml'          # File to read from
          key-path: '["update"]' # Access the runs key then the using key and retuns the value.

      - name: Display read-yaml output
        run: echo "${{ steps.yaml-data.outputs.data }}"
