name: Deploy_to_MB_instances

on:
  workflow_dispatch:
    inputs:
      DEPLOY_HOST:
        description: 'Host to deploing'     
        required: true
        default: 'stage' 
        type: choice
        options:
        - prod
        - stage
      DEPLOY:
        description: 'DEPLOY'
        required: false 
        type: boolean

jobs:
  Deploy_docker_image_stage:
    name: deploy_stage
    runs-on: [self-hosted, linux, X64, stage]
    if: ${{ github.event.inputs.DEPLOY_HOST }} == 'stage'
    env:
      WORK_DIR: ${{ secrets.STAGING_WORK_DIR }}
    steps:

    - name: Deploy
      id: deploy
      run: |
        cd ${{ env.WORK_DIR }}
        ls -la

  Deploy_docker_image_prod:
    name: deploy_prod
    runs-on: [self-hosted, linux, X64, stage]
    if: ${{ github.event.inputs.DEPLOY_HOST }} == 'prod'
    env:
      WORK_DIR: ${{ secrets.PROD_WORK_DIR }}
    steps:

    - name: Deploy
      id: deploy
      run: |
        cd ${{ env.WORK_DIR }}
        ls -la
